### ISSUE TITLE
Board outline on copper layers can result in fabrication shorts.

### ISSUE THREAD

**Issue by tekdemo** [retrostage/SNES-SuperFX-adapter#1]
The gerbers provided have the outline duplicated on all layers, which generates copper layer gerbers that have shorts all over the place, as shown here

![image](https://user-images.githubusercontent.com/526701/65721843-bc77e600-e05f-11e9-9ca0-b88b1c93b5c0.png)

To get the boards as intended, rather than as provided, a fab would need to detect and correct this automatically. Otherwise, the resulting board has all contacts shorted.

Of particular note, OSH Park (my employer) does not correct for this, as doing so in an automated process will interfere with boards that rely on it for various design elements. 

Generally, resolving this is extremely straightforward, by simply adjusting some CAM settings. Usually it's either a single option for "put outline on all gerbers" in the main CAM setup, or by removing the outline layer for the individual layer settings.

**Comment by retrostage** [comment]
Interesting. I haven't seen an issue with this before using other PCB manufacturers, and I'd been having them made for over a year at least before I put them on GitHub.

I'll take a look at the design and re-upload with your suggested change, hopefully to prevent this issue happening.
