### ISSUE TITLE
Question about the OSHPark compatibility

### ISSUE THREAD

**Issue by jon-nielsen** [retrostage/SNES-SuperFX-adapter#2]
Hello. Thanks for making this project available.

On uploading the OSHPark subfolder I get this notification: "Removed empty file "SuperFX_revC.GBP". "

However the file is clearly not empty. Is this expected behavior?

Thanks again

Jon

**Comment by retrostage** [comment]
I've never used OSHpark for these personally, but I've heard that they work fine.

I just uploaded the original board file into the repo in the OSHPark folder. I tried using that in OSHPark and it didn't throw any errors, so it should work for you.

**Comment by retrostage** [comment]
Added download here : [https://github.com/retrostage/SNES-SuperFX-adapter/raw/master/SuperFX%20Gerbers/Fixed%20for%20OSHpark/SuperFX_revA_final.brd](url)

**Comment by jon-nielsen** [comment]
Thank you for your answer - I'm sure you're correct. I'll give that a try :-)
