### ISSUE TITLE
GSU-2 compatibility

### ISSUE THREAD

**Issue by AndehX** [retrostage/SNES-SuperFX-adapter#3]
Just wondering if this adapter definitely works with GSU-2 carts, as these use 40 pin ROM's as opposed to the 32 pin ROM on the GSU-1 carts.

**Comment by retrostage** [comment]
Yes, there are extra pins on the left side where the MaskROM sits that will not be soldered to the adapter pins - which is fine because they're just extra VCC and GND pins anyway. These also work in 40 pin CX4 carts like MegaMax X3.

**Comment by AndehX** [comment]
cool, thanks for clarifying

**Comment by AndehX** [comment]
So im trying to get this to work with Star Fox 2, but im having no luck.  I've flashed the chip properly and verified the data on it.  ucon64 confirms no header and CRC is OK, but im just getting a blank screen on my SNES.  Any ideas?
Heres some image of the install:

![PXL_20210831_143527657](https://user-images.githubusercontent.com/29230701/131524060-cf796701-9b96-4b41-b84b-9a0a8c6aee31.jpg)
![PXL_20210831_144005025](https://user-images.githubusercontent.com/29230701/131524072-b744f81e-768f-4bc2-8a41-246425dae6c6.jpg)
![PXL_20210831_144033359](https://user-images.githubusercontent.com/29230701/131524077-5465428a-2b41-40ed-aa3c-411c8eb1ba70.jpg)

**Comment by retrostage** [comment]
Looks like you've replaced the SRAM. Did you verify that it's all wired up and the correct type for SF2? Other than that, if you have a multimeter you can use the continuity mode to check each pin on the adapter/flash memory to make sure you didn't damage any pins during removal of the old maskrom.

**Comment by AndehX** [comment]
Yeah I already buzzed out all the pins and they all seem fine.  This is actually the second cart I tried this on (in case the first one was messed up somehow)  The SRAM is a 1024KB chip (commonly used for Gradius III SA-1 carts)  I assume it should work ok.  Would that cause any issues? Should I put the original 256K SRAM back?

**Comment by retrostage** [comment]
I'd recommend putting the old one on and test again. I'm not familiar with
changing out the SRAM on these boards, the pinout differences, or how it
affects the games that use it.

**Comment by AndehX** [comment]
Yeah with the original SRAM, it's still the same.  I also tried padding the ROM to 2MB (to fill the 29F016 chip) no dice.  I'm literally out of ideas now.  I removed the chip, read the ROM back from the chip and it loads fine in BSNES, so i'm 95% sure I've flashed the chip properly

**Comment by retrostage** [comment]
Do you have a normal GSU-1 board on hand that you can try the adapter in?

**Comment by AndehX** [comment]
I don't unfortunately.  Only GSU-2 boards

**Comment by retrostage** [comment]
Apparently SF2 requires 512K of SRAM, so the 256K you put back in won't cut it.

Have you compared the pinout of the SRAM you selected to the one the donor cart used?

**Comment by AndehX** [comment]
Ok I figured it out. It seems for some odd reason GSU-2 boards (or at least the Yoshi's Island ones I have) are missing address line A15 on the SRAM.  I had to lift that address line on the SRAM and manually wire it to pin 105 of the GSU-2.  It's working now.

This might be something you want to mention in the documentation for your adapter.

**Comment by retrostage** [comment]
Glad you got it figured out, and that the adapters were working fine.

**Comment by AndehX** [comment]
Yeah.  Just really confused why SRAM A16 would be connected... but not A15.  Super weird.

![PXL_20210831_192006586](https://user-images.githubusercontent.com/29230701/131563280-4aec6a5c-a41a-4d73-8085-86732dbe4925.jpg)

**Comment by AndehX** [comment]
I know you've closed this, and it is technically fixed (not related to the adapter) but im getting crashing now. usually after a minute or 2 of the starfox 2 intro looping.  Any ideas what could cause that?  Sometimes the 3d models disappear, other times the game just glitches and freezes

**Comment by retrostage** [comment]
I'd suspect the SRAM. You're giving 1Mbit of it when the game expects only 512K. Try grounding A16 on the SRAM to see if that helps.

**Comment by AndehX** [comment]
Yeah I had the same idea literally as I posted my previous comment.  Didn't seem to do anything though.

**Comment by AndehX** [comment]
I'm going to leave it for tonight.  I'll try flashing the rom normally again tomorrow (without padding to 2MB)

**Comment by retrostage** [comment]
Maybe try one with a game that natively uses the GSU-2 chip, like Yoshi's
Island or something. I've never made one with SF2 on a FX-2 board before,
so maybe there is some kind of issue due to the different clock speed.

I'll leave this ticket closed for now. As long as the game boots up and
plays it's not a problem with the design of the adapter itself, it's likely
some other issue at hand. But I'd be interested in hearing how things go on
your end regardless.

**Comment by AndehX** [comment]
Ok so I did some testing tonight.  Original Star Fox runs perfectly.  Star Fox 2 still shows graphical glitching and random freezing.  Tried 2 different roms (from 2 different places) and both show the same issue.  So i'm thinking either there's an issue with the type of flash im using (29F016) or the SRAM chip im using.  I'm inclined to believe the SRAM is probably at fault.  I have some different 1Mbit chips ordered (I can't find any compatible 512Kbit chips), and I will test those when they arrive.

**Comment by retrostage** [comment]
I wouldn't think the flash is at fault, as the one you used is fully
pin-compatible with the adapter (all extra unsoldered legs on your chip are
NC anyway). I'd probably suspect the SRAM too, especially if the flash data
also verified correctly.

**Comment by AndehX** [comment]
> I'd probably suspect the SRAM too, especially if the flash data also verified correctly.
>
Yeah especially since original Starfox seems to run perfectly fine.
One difference I did notice between the GSU-1 and GSU-2 boards, is that the /CE pin on the ROM chip is grounded on the GSU-1 board, but connects to pin 20 of the GSU-2-SP1 chip on GSU-2 boards.  Does that matter?

**Comment by AndehX** [comment]
Ok so I tried a different SRAM chip today (SONY CXK581000AM) and the result is the same (although the freezing is less frequent) it seems more stable with this chip, but ultimately, it still crashes now and then and has minor graphical glitches.
It seems like i'm not going to get anywhere with this unless I can source a 512Kbit chip.
